---
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.7
  - ruby-head
jobs:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler -v 2.1.2
install:
  - bundle install
before_script:
  - bundle exec rake compile
script:
  - bundle exec rake spec
after_script:
  - bundle exec rake clean
  - bundle exec rake clobber
