---
language: ruby
cache: bundler
dist:
  - precise
  - trusty
  - xenial
  - bionic
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
jobs:
  include:
    - rvm: 2.0
      dist: xenial
    - rvm: 2.1
      dist: xenial
    - rvm: 2.2
      dist: bionic
    - rvm: 2.3
      dist: bionic
    - rvm: 2.4
      dist: bionic
    - rvm: 2.5
      dist: bionic
    - rvm: 2.6
      dist: bionic
    - rvm: 2.7
      dist: trusty
    - rvm: 2.7
      dist: xenial
    - rvm: 2.7
      dist: bionic
    - rvm: ruby-head
      dist: bionic
  allow_failures:
  - rvm: ruby-head
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - yes | gem update --system --force
  - gem update bundler
install:
  - bundle install
before_script:
  - bundle exec rake --trace clean
script:
  - bundle exec rake --trace compile spec
after_script:
  - bundle exec rake --trace clean
